# docker-compose.yml
services:
  chatbot:
    image: chatbot:osf
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    extra_hosts:
      # For Mac/Windows Docker Desktop:
      - "host.docker.internal:host-gateway"
      
      # For Linux, comment the line above and uncomment below:
      # - "host.docker.internal:172.17.0.1"
    restart: unless-stopped